/**
 * This file was generated by awib.bf from hello.bf.
 * It was successfully compiled by GCC.
 */
#include <stdio.h>
#define eM(x) *p*x;
#define eL(x) *(p+x)+=
#define eK(x) *p*x;
#define eJ(x) *(p-x)+=
#define eI(x) *p=x;
#define eH(x) }
#define eG(x) while(*p){
#define eF(x) p+=x;
#define eE(x) p-=x;
#define eD(x) putchar(*p);
#define eC(x) *p-=x;
#define eB(x) c=getchar();if(c>=0)*p=c;
#define eA(x) *p+=x;
char buf[0xffff];
int main(){
char *p=buf;
int c;
eA(6)
eL(1)
eM(12)
eI(0)
eF(1)
eD(0)
eC(4)
eG(0)
eC(2)
eE(1)
eA(3)
eF(1)
eH(0)
eE(1)
eC(1)
eD(0)
eA(7)
eD(0)
eD(0)
eA(3)
eD(0)
eG(0)
eC(3)
eF(1)
eA(1)
eE(1)
eH(0)
eF(1)
eC(5)
eD(0)
eC(3)
eJ(1)
eK(3)
eI(0)
eE(1)
eD(0)
eC(3)
eG(0)
eC(3)
eF(1)
eA(4)
eE(1)
eH(0)
eF(1)
eC(1)
eD(0)
eA(3)
eD(0)
eC(6)
eD(0)
eC(8)
eD(0)
eC(1)
eG(0)
eC(3)
eE(1)
eA(1)
eF(1)
eH(0)
eE(1)
eD(0)
eG(0)
eC(3)
eF(1)
eA(1)
eE(1)
eH(0)
eF(1)
eC(1)
eD(0)
return 0;}
